//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendAppDataModel
{
    using System;
    
    public enum FriendStatus : int
    {
        Follower = 1,
        Friend = 2,
        Pending = 3,
        Decline = 4,
        Blocked = 5
    }
}
