//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendAppDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendAppDataModelContainer : DbContext
    {
        public FriendAppDataModelContainer()
            : base("name=FriendAppDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<WallPostTagsTable> WallPostTagsTables { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<SubscribedTags> SubscribedTags { get; set; }
        public virtual DbSet<UserTokens> UserTokens { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
    }
}
